### ISSUE TITLE
API Error on Node Red

### ISSUE THREAD

**Issue by Kurisutian** [agileek/hassio-addons#10]
I created a bunch of notifications and automations within Node Red running as a Home Assistant addon as well. However all notification to the signal addon result in an API Error in Node Red. 
The thing is, some will get through and be sent some won't. There is no way of telling which makes the notifications kinda unreliable at this point. 
Running the latest HA possible also updated all plugins I have automated my dryer and washing machine to send me a signal message when they are finished. It worked once despite the API error but then without changing anything to Node Red or HA it stopped working and now is not working whatsoever. I can tell that the trigger arrived at the notify node based on the time it'll update on this part. But no message arrives in Signal. 
Maybe it is related to the API error now, but it cannot be seen at this level nor can I see what is going on "behind the curtain".
If there is anything I can do or provide, I'd be happy to and just need to know what and how to do so.
Thanks!

**Comment by MichaelBitard** [comment]
Hi, thanks for this detailed issue.

In my experience, it was always an error on the node-red side (for example a status retrieval that failed and broke the pipeline), but that's not an immutable rule, it could be the signal addon of course.

When you say "No message arrives in signal", you mean on your phone or in the signal addon?

Are you using the custom component or the official signal integration with this addon?

Do you see the logs appearing in the addon logs? here: `https://your-home-assistant/hassio/addon/4a36bbd1_signal/logs`

You should see something like `2020-05-25 08:37:15,633 - root - INFO - Sending Awesome message to +REDACTED, with attachment`.

If not, that can mean 2 things:
1- home assistant did not receive the message
2- the signal addon is down

If you see this log but did not receive the message on you phone, that's really strange and we could try and investigate further.

Anyway, what you can change the log level of the addon to get more logs and paste them here.

Change this: `log_level: INFO` by this `log_level: DEBUG` and restart the addon.

**Comment by Kurisutian** [comment]
Sorry for not being precise enough in my first message. 

So far I need the message to be received in my cellphone. It worked first but stopped yesterday for some reason. Receiving messages within HA is not something I currently would need (I wasn'teven aware of that possibility). So it's outgoing signal messages from HA. 
I'm using the official HA component with this addon. 

I just changed the loglevel and get back with logs asap once I have the message triggered again, thanks!

**Comment by MichaelBitard** [comment]
@Kurisutian any news?

**Comment by Kurisutian** [comment]
@MichaelBitard sorry for not keeping up here. The API Error remains but I receive messages again regularly. Seemed to be a "hickup" of NodeRED or something which worked again after a restart. Couldn't find anything useful in the Logs. So it shows the API Error but sends the message anyway.

**Comment by MichaelBitard** [comment]
Thanks for the update. 
That's strange indeed. 

I'm closing this issue, don't hesitate to reopen if there is something new!
