### ISSUE TITLE
Signal addon will not run

### ISSUE THREAD

**Issue by skylyn** [agileek/hassio-addons#13]
I had the signal add on working previously, but due to some unrelated problems I had to restore a backup of my homeassistant install. It hasn't worked since then.

I've tried uninstalling the add on, rebooting my pi, reinstalling the add on and starting, but I get this same error from the logs. :
`[FATAL tini (6)] exec main failed: No such file or directory`

This is the only log in the "Log" tab from the Home Assistant Supervisor interface. I'm not sure where else to see any relevant logs to this add on. Let me know if there's a better place to look to see what's going on.

**Comment by MichaelBitard** [comment]
Are you still on the same pi?

You have only this log line from the addon "log" tab?

If I had to guess,I'd say the restore messed with the docker image, and you have a "bad" one on your machine. Are you able to connect to you rpi and do a `docker pull` of the image?

If you can't do that, I'll try to publish a new version to force an automatic update of the docker image

**Comment by marecabo** [comment]
Alternatively, if you feel comfortable using the Portainer add-on, you can use it to delete any unused images related to this add-on, so it is pulled again on reinstall of the Signal add-on.

https://github.com/hassio-addons/addon-portainer

**Comment by MichaelBitard** [comment]
Awesome! I did not know it existed as an addon! Thanks for sharing it!

**Comment by skylyn** [comment]
I got this working, thanks
