### ISSUE TITLE
Sync thing fails to start after hassio update

### ISSUE THREAD

**Issue by Veldkornet** [agileek/hassio-addons#14]
**Describe the bug**
```

[start] 20:41:52 INFO: syncthing v1.7.1 "Fermium Flea" (go1.14.4 linux-arm64) teamcity@build.syncthing.net 2020-07-11 18:17:41 UTC
[start] 20:41:52 WARNING: Failed to initialize config: config file version (32) is newer than supported version (31). If this is expected, use -allow-newer-config to override.
[monitor] 20:41:52 INFO: Syncthing exited: exit status 1
[monitor] 20:41:53 WARNING: 4 restarts in 4.387341527s; not retrying further
```

**Runtime (please complete the following information):**
 - Hardware: rpi 4b
 - OS: hassos 4.13
 - Architecture: arm64
 - Home assistant version: 0.114.4
 - Addon Version 1.7.1

**Comment by MichaelBitard** [comment]
That's because the 1.9.0 is out. Upgrading now

**Comment by MichaelBitard** [comment]
Oops, automaticallly closed by the commit message.
Can you confirm it works, and if it does, close the issue?

**Comment by Veldkornet** [comment]
Yup, looks good now. Thanks!
