### ISSUE TITLE
Cannot update signal add-on to 10.10.0 from home assistant

### ISSUE THREAD

**Issue by kevdliu** [agileek/hassio-addons#16]
Hello, 

I've been running into a persistent error trying to update the signal add-on from 10.9.3 to 10.10.0. This is what I get in the logs

20-11-21 04:38:16 INFO (SyncWorker_0) [supervisor.docker.interface] Updating image agileek/hassio-armv7-signal:10.9.3 to agileek/hassio-armv7-signal:10.10.0
20-11-21 04:38:16 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image agileek/hassio-armv7-signal with tag 10.10.0.
20-11-21 04:38:17 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install agileek/hassio-armv7-signal:10.10.0 -> 404 Client Error: Not Found ("manifest for agileek/hassio-armv7-signal:10.10.0 not found: manifest unknown: manifest unknown").
20-11-21 04:38:17 INFO (SyncWorker_0) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 21.9 GiB

In the end it says it's often caused by not having enought disk space, but I have 21.9GiB available so I don't think that's the reason in this case. I'm running Home Assistant 0.118.2 on Home Assistant OS 4.17 on a Raspberry Pi 4. 

Any help would be apprecaited!

**Comment by MichaelBitard** [comment]
Hello,

That's because this image does not exist on docker hub.
The real issue is, signal-cli (the lib I rely on) recently updated its minimum java version needed to run. Unfortunately, there is not java11 ready for armv7 on alpine, but I think I will be able to make it work soon.

I keep this issue open to track this.

**Comment by kevdliu** [comment]
Thank you for the update, glad there'll be a fix soon

**Comment by MichaelBitard** [comment]
Should be good now!

**Comment by kevdliu** [comment]
works now, thank you!
