### ISSUE TITLE
Improvement: Support for attachments

### ISSUE THREAD

**Issue by rradar** [agileek/hassio-addons#2]
Hello and thank's once again!

I'm using this hassio addon and it works great since the first day. What I'm actually missing is the support to attach one or more files. It would be pictures and/or videos in my case but should not need to limited to this file types. :file_folder:

**Comment by MichaelBitard** [comment]
I want it too, I was waiting for some motivation to implement it.
Motivation you just provided, I'll try to work on it tonight! No promises
though ;)

**Comment by MichaelBitard** [comment]
I added the attachment part in the 10.0.0 version. You'll have to update the plugin and the addon at once.

Right now there is only one attachment possible, I'm battle testing it before adding multiple attachments.

Feel free to re-open if it does not work!
