### ISSUE TITLE
Sending a file

### ISSUE THREAD

**Issue by 14roiron** [agileek/hassio-addons#22]
Hello, thanks for the nice plugin,

2 things, 
For the documentation, can you add that the structure of the signal data should look like that in home assistant:
`/config/.signal/data/+6655456`
As I spend 2 days trying to debug the code, as I was Using this structure:
`/config/.signal/+6655456`

Then, When i try to send a file:
Service notify.signal
```
message : fdedez
data:
   file: /config/www/doors/cam_2021_2_22_12_53.jpg
```
I get this log:
```
2021-02-22 14:05:25,572 - root - INFO - Sending fdedez to +33******, with attachment /tmp/tmpxakuzwyc
2021-02-22 14:05:27,204 - root - DEBUG - <subprocess.Popen object at 0x7f8777c6***>
2021-02-22 14:05:29,403 - root - DEBUG - receiving new line "Envelope from: +33******  (device: 1)"
2021-02-22 14:05:29,404 - root - DEBUG - receiving new line "Timestamp: 1613999126464 (2021-02-22T13:05:26.464Z)"
2021-02-22 14:05:29,405 - root - DEBUG - receiving new line "Got receipt."
2021-02-22 14:05:29,405 - root - DEBUG - receiving new line ""
```

The file is sent, but the received file is tmpxakuzwyc, without any extension and as such, is not shown as an image on signal app.
Screenshot in PJ
![20210222_143543](https://user-images.githubusercontent.com/9865489/108715885-ba97a800-751b-11eb-9ead-1d739cff9601.jpg)

If I try to rename it, The file can be seen as a picture

Thanks for your help

**Comment by MichaelBitard** [comment]
Hello,

You're welcome!

Well spotted for the documentation, I'll add that to the README.

For your issue, that's strange, it works on my machine :tm: 

I receive some svg and png daily, without issue. I just tried with a jpg too and it works.

I'll need more information to investigate, are you using the last version of the addon? what signal app are you using to receive the messages ? I tested and it works on android and with the signal app on linux

**Comment by 14roiron** [comment]
Thanks for your quick answer,

Setup is hassio on a VM, Amd64

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-02-22 18:16:40 +0100] [202] [INFO] Starting gunicorn 20.0.4
[2021-02-22 18:16:40 +0100] [202] [INFO] Listening at: http://0.0.0.0:5000 (202)
[2021-02-22 18:16:40 +0100] [202] [INFO] Using worker: sync
[2021-02-22 18:16:40 +0100] [205] [INFO] Booting worker with pid: 205
SETTING LOG LEVEL TO 10
2021-02-22 18:16:41,065 - root - INFO - Init
2021-02-22 18:16:41,069 - root - INFO - Listening to incoming messages
2021-02-22 18:16:41,069 - root - INFO - Process started and listening on 4a36bbd1-signal
INFO DaemonCommand - Exported dbus object: /org/asamk/Signal
```
This is the start up screen.

 I have the latest version on android and mac.
version  10.11.2 for Hassio Addon

And I downloaded your component few days ago, so it should be the last version.


I thought it was due to 
```
            if data is not None and ATTR_FILE in data:
                files['file'] = (data.get(ATTR_FILE), open(data.get(ATTR_FILE), 'rb'), 'application/octet-stream')
``` 
in notify.py of the component, as the file is detected as an octet stream
I will try to run some tests

**Comment by MichaelBitard** [comment]
The octet-stream is the way to send the data to the http server, but maybe you could try and tweak it. 
Is your number trusted? Maybe it's some "security" from signal.

If you want, you can DM (via twitter?) me your phone number and I'll send you a message from my hassio addon with a picture to see if it works?

**Comment by 14roiron** [comment]
If I use an image from the Web, it seems to be working fine
I am trying to investigate why my pictures are causing issues

**Comment by MichaelBitard** [comment]
that's interesting, in your image generated from a camera stream? maybe you are missing some headers

**Comment by 14roiron** [comment]
That's coming from the hassio automation and one of my camera:

```
alias: Take ScreenShot
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d0000000000_contact
    attribute: friendly_name
    from: Closed
    to: Open
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: camera.snapshot
    data:
      filename: >-
        /config/www/doors/cam_{{ now ().year }}_{{ now ().month }}_{{ now ().day
        }}_{{ now ().hour }}.jpg
    entity_id: camera.reolink_profile000_mainstream
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: notify.signal
    data:
      message: Door Open
      data:
        file: >-
          /config/www/doors/cam_{{ now ().year }}_{{ now ().month }}_{{ now
          ().day }}_{{now ().hour }}.jpg
mode: single

```
and this is the ouput of a file command:
``` file tmpyelfu0fz                                                          
tmpyelfu0fz: JPEG image data, baseline, precision 8, 2560x1920, components 3```
The hashes are the same before sending to signal and after.

Let me try another camera. I don't know if the snapshot function is manager by HA or the camera itself, but it's not a bug on signal integration
Thanks
yohann

**Comment by 14roiron** [comment]
[cam_2021_2_22_20_32.jpg.zip](https://github.com/agileek/hassio-addons/files/6024792/cam_2021_2_22_20_32.jpg.zip)
All my camera give me the same file format, even though one use Onvif and the other one, the mjpeg driver, here is a file if you want to try

**Comment by kevdliu** [comment]
I ran into this issue with images generated by my IP cameras as well. It seems like signal detects the format of the file via some sort of metadata instead of the file extension. The images generated by the IP cams do not contain that metadata and therefore signal does not show them as images. I ended up writing a simple custom component which basically uses PIL to convert the images into jpgs, which added the required metadata and fixed the issue.

**Comment by 14roiron** [comment]
that's why the telegram integration require an additionnal tag as described here:
https://community.home-assistant.io/t/ip-camera-snapshot-automation/41319/3

**Comment by MichaelBitard** [comment]
I can reproduce you problem with your file indeed. I think we should open an issue to signal to see if there is something that could be done on their side, or something we should ensure before sending the image.

The bug appears on android and linux desktop. Can I use your image for the signal issue @14roiron?

**Comment by MichaelBitard** [comment]
I think I could also try to fix it by not sending a random file name but rather using the filename given as parameter

**Comment by MichaelBitard** [comment]
The octet-stream is not the issue IMHO, because it's the communication side between the home assistant integration and the hassio docker addon, not between the hassio docker addon and the signal server.

**Comment by MichaelBitard** [comment]
It works \o/

@14roiron can you test it too? and close the issue if that's ok

**Comment by 14roiron** [comment]
Perfect it s working for both photo and videos 
thank you very much 👍
