### ISSUE TITLE
Consider adding signalmessenger custom component to docker ignore

### ISSUE THREAD

**Issue by JayNewstrom** [agileek/hassio-addons#3]
There shouldn't be a reason to include the custom component in the addon docker container.

I'd be happy to send a PR setting it up if you're interested.

**Comment by MichaelBitard** [comment]
You are completely right, you can do the PR if you want, I'll merge it. Or I'll add this myself when I work on it again ;)

**Comment by JayNewstrom** [comment]
So it's really not that big of a deal, since root is the only thing getting copied. But I think it's the right thing to do to ignore basically everything else!

PS, thanks for creating this! I'm using it :)
