### ISSUE TITLE
Signal: WS authentication error when sending messages to Home Assistant

### ISSUE THREAD

**Issue by kevdliu** [agileek/hassio-addons#42]
**Describe the bug**
When I send messages to home assistant for intent script, I get "Something bad happened" as the reply. This is what I see in the logs:

`2022-07-04 01:25:13,981 - root - INFO - message received {'sender': '+1**********', 'message': '***'}
2022-07-04 01:25:13,984 - root - INFO - Sending message to ws://supervisor/core/websocket
2022-07-04 01:25:14,087 - root - ERROR - could not authenticate with home assistant {'type': 'auth_invalid', 'message': 'Invalid access'}
2022-07-04 01:25:14,096 - root - INFO - Sending "Something bad happened" to +**********`

Unrelated but I also see this warning:
`WARN  ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name wit the updateProfile command. This may become mandatory in the future.`

**To Reproduce**
Setup intent script and send any message to home assistant

**Runtime (please complete the following information):**
 - Hardware: ODroid N2
 - OS: HASS OS
 - Architecture: arm64
 - Home assistant version: 
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
 - Addon Version: 10.19.3

**Comment by MichaelBitard** [comment]
Yes I see that too.

Did they change the way we authenticate to the websocket?

I'll look into the docs and try to fix this

**Comment by MichaelBitard** [comment]
I embedded a fix in https://github.com/agileek/hassio-addons/pull/41

Should be good, can you confirm it works?

**Comment by MichaelBitard** [comment]
Nop, does not work :(

**Comment by MichaelBitard** [comment]
Let's try that,

![ihave](https://user-images.githubusercontent.com/414642/178207767-8ca0bc2d-96a6-4a53-a993-c167c83ba018.jpg)

The addon documentation becomes more and more obscure IMHO, with parameters that have almost the same name, and a really succinct description.

I asked for help on discord, but could not get anything either...

**Comment by MichaelBitard** [comment]
Still the same message....

**Comment by MichaelBitard** [comment]
Ok, something new appeared. Apparently, the environment variable containing the token is not passed anymore in the asynchronous context.

I'll try something new, that's promising

**Comment by kevdliu** [comment]
Apparently this guy also ran into the problem of SUPERVISOR_TOKEN becoming undefined after setting init to false: https://community.home-assistant.io/t/hello-world-example-addon-from-developer-docs-stopped-working-s6-overlay-issue/421486/11

And he later replied that setting hassio_role to default fixed it: https://community.home-assistant.io/t/hello-world-example-addon-from-developer-docs-stopped-working-s6-overlay-issue/421486/17

Which is weird because that should be the default value, but I guess it's worth a shot ¯\_(ツ)_/¯

**Comment by MichaelBitard** [comment]
I already did taht and it changed nothing. But it is fixed now, can you test it? I remove the defaut init entrypoint of the docker image, it seems to prevent the environment variables from being passed

**Comment by MichaelBitard** [comment]
You're welcome. I a curious about your usages of this feature :)

**Comment by kevdliu** [comment]
> You're welcome. I a curious about your usages of this feature :)

I use it as action shortcuts when getting alerts. For example, I have home assistant set up to alert me via signal when I leave home without arming the alarm. I can simply reply "arm" to arm the alarm instead of having to open the alarm app. Same with turning off lights etc. It's super useful!
