### ISSUE TITLE
Signal doesn't work anymore - status cod 499

### ISSUE THREAD

**Issue by carolinaxxxxx** [agileek/hassio-addons#45]
Please update: https://github.com/AsamK/signal-cli/issues/1022

**Comment by MichaelBitard** [comment]
I'm on it, I have to rebuild libsignal

**Comment by MichaelBitard** [comment]
related to https://github.com/signalapp/libsignal/issues/481

It could take a while for me to figure this out :(

**Comment by carolinaxxxxx** [comment]
If there is a compilation problem, perhaps this will help:

cd signal-cli-0.11.1/lib/
mkdir tmp
cd tmp
unzip ../signal-cli-0.11.1.jar 
sed -i 's/Signal-Android\/5.22.3/Signal-Android\/5.51.7/g' org/asamk/signal/BaseConfig.class 
zip -r ../signal-cli-0.11.1.jar org/ META-INF/

https://github.com/AsamK/signal-cli/issues/1022#issuecomment-1269169653

**Comment by tholland15** [comment]
> related to [signalapp/libsignal#481](https://github.com/signalapp/libsignal/issues/481)
> 
> It could take a while for me to figure this out :(

If I'm reading this correct the armv7 builds are blocked?

If so, could we do a temporary release without armv7 support for those of us running x86-64 or arm64?

**Comment by tholland15** [comment]
BTW I could help get a build pipeline set up in github actions if interested and if you deem it worth it (not sure how often libsignal has to be recompiled). 

I have experience compiling for arm in github actions using qemu virtualization instead of cross compiling.

**Comment by MichaelBitard** [comment]
That could be interesting @tholland15, because I cannot build for armv7, arm64 nor x86-64 with cross at the moment.

All of them fail...

I don't have the physical machines to try and build on it.

You can look at the readme here https://github.com/agileek/hassio-addons/tree/master/signal/root/ext/libraries/libsignal-client on how I build them with cross.

If you can provide me the libsignal_jni.so for these archs, I could add them and fix the addon.

We could look at a way to integrate this in the CI in a second time

**Comment by tholland15** [comment]
I should have time to work on this tomorrow, just took a look and it doesn't look too difficult. 

My plan is to create a GitHub Action that when run will download libsignal-client, compile it for the 3 architectures and then commit the 3 libsignal_jni.so files to the repo. 

Will open a PR when I'm done for both the files and a separate PR for the GitHub Action so you can add it if you like.

**Comment by MichaelBitard** [comment]
That would be Amazing \o/

**Comment by tholland15** [comment]
@MichaelBitard PR #47 opened.

I was debugging some minor issues that were preventing the arm64 and armv7 binaries from being committed, but I expect my current run to pass the the PR to be updated with those binaries once my current run completes. 

I notice on the PR the note that: `The base branch requires all commits to be signed.`  So either changes will need to be made to sign the commits via github actions https://github.com/actions/runner/issues/667, or this branch protection rule will need to be tweaked.

**Comment by MichaelBitard** [comment]
Amazing work, thanks. I'll update the signal addon right now and see if everything works

**Comment by tholland15** [comment]
#49 is ready for review, which commits the binaries to a new PR on building, instead of trying to commit to master directly. I expect that would solve the branch protection issues.

**Comment by MichaelBitard** [comment]
I deployed the new version, it seems to work on sending messages from home assistant to signal.

There is a bug though when receiving messages, I'm fixing it on #50 

Thanks @tholland15 for your work on libsignal, I only played with cross before and did not think of using arm-runner-action.

If everything works, you can close the issue @carolinaxxxxx

**Comment by MichaelBitard** [comment]
version 10.20.1 works flawlessly on my home assistant instance

**Comment by tholland15** [comment]
Thanks @MichaelBitard! I use signal for all of my notifications from HA and am very glad to be back up and running! Great work on this addon and thanks for allowing me to contribute.
