### ISSUE TITLE
Signal: WS error when sending messages to Home Assistant

### ISSUE THREAD

**Issue by kevdliu** [agileek/hassio-addons#55]
**Describe the bug**
New year, new home assistant, new WS error :)

This is what I see in the addon logs when I send a message to home assistant:
```
2023-01-13 17:54:54,382 - root - INFO - message received {'sender': '+XXX', 'message': 'ASDFF'}
2023-01-13 17:54:54,383 - root - INFO - Sending message to ws://supervisor/core/websocket
2023-01-13 17:54:54,430 - root - ERROR - Unexpected error 'speech'
2023-01-13 17:54:54,431 - root - INFO - Sending "Something bad happened" to +XXX
```

I have no idea what this "speech" exception is. 

**To Reproduce**
Setup intent script and send any message to home assistant

**Runtime (please complete the following information):**
Hardware: ODroid N2
OS: HASS OS
Architecture: arm64
Home assistant version:
Home Assistant Core 2023.1.1
Home Assistant Supervisor 2022.12.1
Home Assistant OS 9.4
Addon Version: 10.20.1

**Comment by MichaelBitard** [comment]
Mmh, that is indeed strange...
Can you try at log level debug to see if something pops up?

**Comment by MichaelBitard** [comment]
I'm deploying a new patch to see if we can have better error message (10.20.2)

**Comment by kevdliu** [comment]
This is the WS from home assistant:
`{'id': 1, 'type': 'result', 'success': True, 'result': {'response': {'speech': {'plain': {'speech': 'THIS IS THE ACTUAL RESPONSE', 'extra_data': None}}, 'card': {}, 'language': 'en', 'response_type': 'action_done', 'data': {'targets': [], 'success': [], 'failed': []}}, 'conversation_id': None}}`

Looks like they wrapped everything in a "speech" object. So I guess now we need to do `conversation_response['result']['speech']['speech']['plain']['speech']`

**Comment by MichaelBitard** [comment]
Thanks, that's what I saw from the documentation too.

Too bad there is not a deprecation mechanism from home assistant :(

This should fix it: https://github.com/agileek/hassio-addons/commit/ff983846663487fcd2400c26d616de30301e105a

**Comment by kevdliu** [comment]
That fixed it! Thanks for the quick update. Disappointing that they didn't include the breaking change in their changelog.

**Comment by MichaelBitard** [comment]
You're welcome, and thanks to you too for the sponsoring :heart:
