### ISSUE TITLE
The Synching addon keeps on restarting due to a repeated update that is being executed

### ISSUE THREAD

**Issue by Veldkornet** [agileek/hassio-addons#63]
The Synching addon keeps on restarting due to an update that's available. 
It successfully updates, but after a restart it's back on the old version and starts the whole process again.
Log:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[start] 2023/07/06 04:44:50 INFO: syncthing v1.23.5 "Fermium Flea" (go1.20.4 linux-arm64) builder@github.syncthing.net 2023-06-06 07:06:51 UTC
[GSNLI] 2023/07/06 04:44:52 INFO: Connected to device XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX with a newer version (current "v1.23.5" < remote "v1.23.6"). Checking for upgrades.
[GSNLI] 2023/07/06 04:44:52 INFO: Automatic upgrade (current "v1.23.5" < latest "v1.23.6")
[GSNLI] 2023/07/06 04:44:54 WARNING: Automatically upgraded to version "v1.23.6". Restarting in 1 minute.`

_Originally posted by @thefoxmangit in https://github.com/agileek/hassio-addons/issues/52_

**Comment by MichaelBitard** [comment]
hi @Veldkornet is this ok now?

**Comment by Veldkornet** [comment]
Yes, seems to be okay now after the last update
