### ISSUE TITLE
Unable to execute `notify.signal`

### ISSUE THREAD

**Issue by corneels** [agileek/hassio-addons#7]
I have successfully configured this addon to receive messages and reply to them based on the configuration of `intent_script:` and `conversation:` in `configuration.yaml`. I get a successful `Hello there!` back as expected.

However, I am unable to use `notify.signal` successfully to send a message. I am also unable to run `signalmessenger.get_groups`.

I get the following error when running `notify.signal`:

```
HTTPConnectionPool(host='4a36bbd1-signal', port=5000): Max retries exceeded with url: /message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xad892270>: Failed to establish a new connection: [Errno -3] Try again'))
```

And the following error when running `signalmessenger.get_groups`:

```
HTTPConnectionPool(host='4a36bbd1-signal', port=5000): Max retries exceeded with url: /group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xad7497b0>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by MichaelBitard** [comment]
* Are you using the official signal?
  * If yes, can you show me your configuration?

Can you show me what you try to send using the developer tools?

Also, can you send me the logs of the signal addon?

I just tried both (the custom_component and the official addon) and it works fine on my machine :tm: 

It's possible I missed something in the readme, but without more information it'll be difficult to pinpoint the issue

**Comment by corneels** [comment]
Hello, thanks for your reply.

If you mean to ask if I am using the official signal integration, I am not using it - I am using the custom component. Perhaps I can try the official addon to troubleshoot. What url should I specify in my configuration?

My `configuration.yaml`:
```
intent_script:
  Test:
    speech:
      text: Hello there!

conversation:
  intents:
    Test:
      - Test
      - This is a test

signalmessenger:
notify:
  - name: signal
    platform: signalmessenger
    destinations:
      - "+61412345678"
```

In `/config/custom_components/signalmessenger`, the following files are present:
```
__init__.py
__pycache__/
const.py
notify.py
test_notify.py
```

When I run `notify.signal` and `signalmessenger.get_groups`, no logs are generated by the signal addon.

Here are the pertinent lines from `home-assistant.log`: [error.log](https://github.com/agileek/hassio-addons/files/4486627/error.log)

Here are the logs that the addon produced after I rebuilt the addon: [addon.log](https://github.com/agileek/hassio-addons/files/4486632/addon.log)

**Comment by corneels** [comment]
Also, the config of the addon:
```
phone_number: '+61412345678'
signal_config_path: /config/.signal
```

**Comment by MichaelBitard** [comment]
Ok thanks for the logs.

I updated the addon to see what could be missing.
Can you update to the `10.7.1`? You should have a new log message like this:

```
2020-04-16 13:34:12,692 - root - INFO - Init
2020-04-16 13:34:12,703 - root - INFO - Process started and listening on 4a36bbd1-signal
```
Is this exactly `4a36bbd1-signal` and not something else?

**Comment by corneels** [comment]
```
[2020-04-16 21:43:27 +1000] [301] [INFO] Starting gunicorn 20.0.4
[2020-04-16 21:43:27 +1000] [301] [INFO] Listening at: http://0.0.0.0:5000 (301)
[2020-04-16 21:43:27 +1000] [301] [INFO] Using worker: sync
[2020-04-16 21:43:27 +1000] [303] [INFO] Booting worker with pid: 303
2020-04-16 21:43:28,510 - root - INFO - Init
2020-04-16 21:43:28,518 - root - INFO - Process started and listening on 4a36bbd1-signal
```

**Comment by corneels** [comment]
Don't know if this carries any relevance, but I am using an NGINX Home Assistant SSL Proxy.

**Comment by corneels** [comment]
Logs when I send `Test` from my mobile phone:
```
2020-04-16 21:45:19,483 - root - INFO - message received {'sender': '+my_number', 'message': 'Test'}
2020-04-16 21:45:19,485 - root - INFO - Sending message to ws://supervisor/core/websocket
2020-04-16 21:45:19,510 - root - INFO - Connecting to websocket
2020-04-16 21:45:19,512 - root - INFO - Connected to websocket
2020-04-16 21:45:19,518 - root - INFO - Authenticated to websocket
2020-04-16 21:45:19,641 - root - INFO - Sending Hello there! to +my_number, with attachment 
2020-04-16 21:45:26,228 - root - INFO - <subprocess.Popen object at 0xb6263d60>
```

**Comment by MichaelBitard** [comment]
Mmh, I don't know. I think it's not relevant because the custom component communicate with the hassio addon using docker networks, so they are not using ssl or anything.

**Comment by corneels** [comment]
Okay, not sure what changed, but we're in business... Sent a message, success. Get groups, success.

I did update my home assistant version to latest, and obviously uninstalled and updated to your latest addon.

Now that I've installed the official addon I do have an issue with that, but I think you've helped me enough for one day 🥇 

Thanks for your quick response.

**Comment by MichaelBitard** [comment]
That's really strange, maybe the addon took some time to connect, I don't really know.

Don't hesitate to open a new issue for the official addon, I'll gladly help.

On my machine, I try it with this configuration:

```yaml
  - name: official_signal
    platform: signal_messenger
    url: "http://4a36bbd1-signal:5000"
    number: "+yourphonenumber"
    recipients:
      - "+yourphonenumber"
```
I think only one of them is needed (number or recipients) but I don't remember which :)

**Comment by MichaelBitard** [comment]
Anyway, I'm glad it works!

**Comment by corneels** [comment]
Thanks for that URL for the official signal integration. I tested it and it successfully messages me. Strangely, it gives me an error that it didn't send, though... Ah well. An issue for another day.
