### ISSUE TITLE
For two days, error in HA

### ISSUE THREAD

**Issue by carolinaxxxxx** [agileek/hassio-addons#73]
Log:

Error while checking account xxx: signal-cli version is too old for the Signal-Server, please update.

**Comment by tholland15** [comment]
seeing the same thing @MichaelBitard

**Comment by MichaelBitard** [comment]
I'm not sure I can do anything, I'm using the last signal-cli version. I'm creating an issue on the other repo to track it :cry:

**Comment by MichaelBitard** [comment]
Ok I see, I'll push a fix right now

**Comment by tholland15** [comment]
A sincere thank you for the rapid response, as always!

**Comment by MichaelBitard** [comment]
It's building right now, you can update once https://github.com/agileek/hassio-addons/actions/runs/7832319329 is green :crossed_fingers:
